apiVersion: v1
kind: Secret
metadata:
  name: dft-postgresql-secrets
  #namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  dbUrl: "<path:dft/data/postgres#DB_URL>"
  username: "<path:dft/data/postgres#DB_USER>"
  password: "<path:dft/data/postgres#DB_PASSWORD>"
  postgres-password: "<path:dft/data/postgres#DB_POSTGRESPASSWORD>"
  database: "<path:dft/data/postgres#DB_NAME>"
