apiVersion: v2
appVersion: 1.0.0
description: A Helm chart to deploy SFTP
keywords:
- sftp
- openssh
- files
- storage
- ftp
maintainers:
- email: helm-charts@emberstack.com
  name: winromulus
name: sftp
sources:
- https://github.com/EmberStack/docker-sftp
type: application
version: 1.0.0
