apiVersion: v1
kind: Secret
metadata:
  name: dft-postgresql-secrets
type: Opaque
stringData:
  password: {{ .Values.dftpostgresql.auth.secretKeys.adminPasswordKey | default ( randAlphaNum 32 | quote ) }}
  postgres-password: {{ .Values.dftpostgresql.auth.secretKeys.userPasswordKey | default ( randAlphaNum 32 | quote ) }}