apiVersion: v1
kind: Service
metadata:
  name: console
  labels: {{- include "minio-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector: {{- include "minio-operator.console-selectorLabels" . | nindent 4 }}
