name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger the workflow only when a tag starting with 'v' is pushed (e.g., v1.0.0, v2.1.3)

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x' # Choose the appropriate Node.js version

    - name: Install dependencies
      run: npm install # Or yarn install if using Yarn

    - name: Build your project (if applicable)
      run: npm run build # Or any build command specific to your project

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: '' # Optional. Comma-separated list of files to include in the release (e.g., "dist/*,docs/*")
        body: '' # Optional. Release notes or description
        tag_name: v1.1.2
        draft: false
        prerelease: false
